### ISSUE TITLE
Bug - export fails due to unhandled null reference when replacing relative uri

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.Rules.SharePointExtractor#6]
cc @adamcogan @SebastienBoissiere 

"term" is being exported with .FirstOrDefault() 
https://github.com/SSWConsulting/SSW.Rules.SharePointExtractor/blob/2a02eb25586a2e5be36ebf159ef10a5c68914260/SSW.Rules.SharePointExtractor/SSW.Rules.SharePointExtractor/SpImporter/SpImporter.cs#L387

But the null condition is not handled, causing export to fail at:
https://github.com/SSWConsulting/SSW.Rules.SharePointExtractor/blob/2a02eb25586a2e5be36ebf159ef10a5c68914260/SSW.Rules.SharePointExtractor/SSW.Rules.SharePointExtractor/SpImporter/SpImporter.cs#L388

URI being parsed was a "FIXUPREDIRECT" link where term was not in the term collection.
e.g. `/_layouts/15/FIXUPREDIRECT.ASPX?WebId=3dfc0e07-e23a-4cbb-aac2-e778b71166a2&TermSetId=07da3ddf-0924-4cd2-a6d4-a4809ae20160&TermId=257bcb90-884d-49bd-8e15-e639c70f7de1`

1. Please investigate
2. Handle null condition appropriately (not sure what the appropriate approach should be)

**Comment by christianmorfordwaitessw** [comment]
To: @wicksipedia 
Cc: @adamcogan @SebastienBoissiere
> 1. Please investigate

**Done**
> 2. Handle null condition appropriately (not sure what the appropriate approach should be)

**Done** - If the term cannot be found in the term store it keeps the original Uri and logs a warning
https://github.com/SSWConsulting/SSW.Rules.SharePointExtractor/blob/e9cecc2ffce29106cd677dbc852b5b454d360fdc/SSW.Rules.SharePointExtractor/SSW.Rules.SharePointExtractor/SpImporter/SpImporter.cs#L396
